# Generated by Django 5.0.2 on 2024-06-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
